"""empty message

Revision ID: 8f052e641718
Revises: 
Create Date: 2018-06-05 13:40:30.687359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f052e641718'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pounce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placed', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('bet', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('pounced', sa.Boolean(), nullable=False),
    sa.Column('profit', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pounce')
    # ### end Alembic commands ###
